import { test, expect } from '@playwright/test'

test.describe('Horse Racing Game', () => {
  test.beforeEach(async ({ page }) => {

    // Set test mode flag in localStorage before loading the page
    await page.goto('/')
    await page.evaluate(() => {
      localStorage.setItem('__E2E_TEST_MODE__', 'true')
    })
    // Reload to apply the flag
    await page.reload()
  })

  test('loads the game interface', async ({ page }) => {
    await expect(page.locator('h1')).toHaveText('🐴 Horse Racing Game')
  })

  test('shows initial state with disabled Start button', async ({ page }) => {
    // Generate button should be enabled
    const generateBtn = page.getByRole('button', { name: 'Generate' })
    await expect(generateBtn).toBeEnabled()

    // Start button should be disabled
    const startBtn = page.getByRole('button', { name: 'Start' })
    await expect(startBtn).toBeDisabled()

    // Should show "Ready to Generate" status
    await expect(page.locator('.status-indicator')).toContainText('Ready to Generate')
  })

  test('generates 20 horses and 6 rounds schedule', async ({ page }) => {

    // Click Generate button
    await page.getByRole('button', { name: 'Generate' }).click()

    // Wait for horses to be generated
    await page.locator('.horse-card').first().waitFor({ timeout: 2000 })

    // Check that 20 horses are displayed
    const horses = page.locator('.horse-card')
    await expect(horses).toHaveCount(20)

    // Check that 6 rounds are in schedule
    const rounds = page.locator('.round-card')
    await expect(rounds).toHaveCount(6)

    // Check that Start button is now enabled
    const startBtn = page.getByRole('button', { name: 'Start' })
    await expect(startBtn).toBeEnabled()

    // Check status changed to "Ready to Start"
    await expect(page.locator('.status-indicator')).toContainText('Ready to Start')
  })

  test('each horse has unique color and valid condition', async ({ page }) => {
    await page.getByRole('button', { name: 'Generate' }).click()
    await page.locator('.horse-card').first().waitFor({ timeout: 2000 })

    // Get all horse cards
    const horses = page.locator('.horse-card')
    const count = await horses.count()

    expect(count).toBe(20)

    // Check each horse has condition between 80-100
    for (let i = 0; i < count; i++) {
      const conditionText = await horses.nth(i).locator('.stat-value').last().textContent()
      const condition = parseInt(conditionText || '0')
      expect(condition).toBeGreaterThanOrEqual(80)
      expect(condition).toBeLessThanOrEqual(100)
    }
  })

  test('schedule shows correct distances', async ({ page }) => {
    await page.getByRole('button', { name: 'Generate' }).click()

    // Wait for schedule to be generated by checking if round cards exist
    await expect(page.locator('.round-card')).toHaveCount(6, { timeout: 2000 })

    const expectedDistances = ['1200m', '1400m', '1600m', '1800m', '2000m', '2200m']

    // Need to click through tabs to check each round's distance
    for (let i = 0; i < 6; i++) {
      // Click the tab for this round
      await page.locator('.tab').nth(i).click()

      // Check the distance in the active tab
      const roundDistance = page.locator('.round-details .round-distance')
      await expect(roundDistance).toHaveText(expectedDistances[i]!)
    }
  })

  test('each round has 10 horses', async ({ page }) => {
    await page.getByRole('button', { name: 'Generate' }).click()

    // Wait for schedule to be generated
    await expect(page.locator('.round-card')).toHaveCount(6, { timeout: 2000 })

    // Check each round by clicking through tabs
    for (let i = 0; i < 6; i++) {
      // Click the tab for this round
      await page.locator('.tab').nth(i).click()

      // Check that the active round has 10 horses
      const roundHorses = page.locator('.round-details .horse-chip')
      await expect(roundHorses).toHaveCount(10)
    }
  })

  test('completes full race sequence', async ({ page }) => {

    // Generate
    await page.getByRole('button', { name: 'Generate' }).click()
    await page.locator('.round-card').first().waitFor({ timeout: 2000 })

    // Start all 6 rounds sequentially
    for (let round = 1; round <= 6; round++) {
      // Click Start button for current round
      await page.getByRole('button', { name: /Start/ }).click()

      // Check status changed to "Racing Round X/6..."
      await expect(page.locator('.status-indicator')).toContainText('Racing', { timeout: 2000 })

      // Wait for result to appear (increased timeout for slower browsers like Firefox/WebKit)
      await page.locator('.result-wrapper').nth(round - 1).waitFor({ timeout: 20000 })
    }

    // Check all 6 results are present
    await expect(page.locator('.result-wrapper')).toHaveCount(6)

    // Check final status is "Finished"
    await expect(page.locator('.status-indicator')).toContainText('Finished')
  })

  test('shows results with rankings and times', async ({ page }) => {
    await page.getByRole('button', { name: 'Generate' }).click()

    // Wait for schedule
    await expect(page.locator('.round-card')).toHaveCount(6, { timeout: 2000 })

    await page.getByRole('button', { name: 'Start' }).click()

    // Wait for first result wrapper to appear (race takes ~0.5s in test mode with 200x acceleration)
    await page.locator('.result-wrapper').first().waitFor({ timeout: 15000 })

    // Check that the visible result card has 10 rankings
    const firstResult = page.locator('.result-card')
    const rankings = firstResult.locator('.ranking-row')
    await expect(rankings).toHaveCount(10)

    // Check that times are displayed
    const firstTime = firstResult.locator('.ranking-time').first()
    await expect(firstTime).toBeVisible()

    // Check that podium positions have medals
    const firstPlace = firstResult.locator('.ranking-row').first()
    await expect(firstPlace).toContainText('🥇')
  })

  test('Reset button works after game finishes', async ({ page }) => {
    // Generate and complete all races
    await page.getByRole('button', { name: 'Generate' }).click()
    await page.locator('.round-card').first().waitFor({ timeout: 2000 })

    // Complete all 6 rounds
    for (let round = 1; round <= 6; round++) {
      await page.getByRole('button', { name: /Start/ }).click()
      await page.locator('.result-wrapper').nth(round - 1).waitFor({ timeout: 20000 })
    }

    // Verify game is finished
    await expect(page.locator('.status-indicator')).toContainText('Finished')

    // Check Generate button is disabled
    const generateBtn = page.getByRole('button', { name: 'Generate' })
    await expect(generateBtn).toBeDisabled()

    // Check Reset button is available
    const resetBtn = page.getByRole('button', { name: 'Reset Game' })
    await expect(resetBtn).toBeEnabled()

    // Click Reset
    await resetBtn.click()

    // Verify game returned to idle state
    await expect(page.locator('.status-indicator')).toContainText('Ready to Generate', { timeout: 2000 })

    // Check Generate button is now enabled again
    await expect(generateBtn).toBeEnabled()

    // Check no horses are displayed (reset cleared everything)
    const horses = page.locator('.horse-card')
    await expect(horses).toHaveCount(0)

    // Check no results are displayed
    const results = page.locator('.result-wrapper')
    await expect(results).toHaveCount(0)
  })
})
